### ISSUE TITLE
V3 roadmap.

### ISSUE THREAD

**Issue by Pingear** [isoos/postgresql-dart#105]
Hello)
I apologize if the information that interests me is somewhere in the most visible place, but I managed not to notice it, but I have a question about version 3.
1) Why is it called experimental and can it be used and when will it cease to be experimental?
2) What is missing to make it official, is there some kind of roadmap? 
3) If, for example, I want to contribute to the repository, what tasks need to be performed?
I just don't understand why this repository has so few stars when it's practically the only postgresql solution?

**Comment by isoos** [comment]
> Why is it called experimental and can it be used and when will it cease to be experimental?

It is not quite ready yet, but @simolus3 did a tremendous job of pushing it forward.

> What is missing to make it official, is there some kind of roadmap?

More like an ad-hoc plan that soon we will release a version where the API is mostly ready, and people may start to migrate to it, then remove a 3.0.0 where we remove the old API.

> If, for example, I want to contribute to the repository, what tasks need to be performed?

Depends on the scope. For a small fix, just go ahead, do a PR, and make sure the tests pass. For a larger body of work it may be worth to open an issue and discuss it.

> I just don't understand why this repository has so few stars when it's practically the only postgresql solution?

This package was first developed by the Stable Kernel company, but their focus shifted, and I was developing a few Postgres-heavy app at the time, and with their approval I took over the stewardship of the package. This was the original repository: https://github.com/stablekernel/postgresql-dart

**Comment by simolus3** [comment]
I think feature-wise the v3 API should be pretty much ready. But while we have integration tests for it, it doesn't use many parts from the existing implementation and so there's a chance of it having bugs or reliability issues we haven't found yet. It also needs to be documented better.

> More like an ad-hoc plan that soon we will release a version where the API is mostly ready, and people may start to migrate to it, then remove a 3.0.0 where we remove the old API.

Maybe we could setup a `v3` branch in this repository and prepare a package version that only has the v3 API on that branch? Perhaps it could be published it as `3.0.0-beta` or something to pub to encourage users to try it out.
The "experimental" label might discourage users from adopting it since it sounds like everything is subject to change, but from my point of view the API surface turned out to be pretty solid and probably won't require breaking changes.

**Comment by isoos** [comment]
I think the v2 is good as-is, and if we want to go ahead with the v3 release, we just do it, no need for a separate `v3` branch. Maybe we should migrate / adapt the v2-tests to the new API, and if those pass, we are just call it a day? It also makes it clear what we may need to put in the migration guide...

**Comment by Pingear** [comment]
If a third version is coming, that's great news! Support for the connection pool, or rather its absence in the second version, is the first thing I noticed. Then I discovered this functionality in Serverpod, and I was very happy when I realized that the package that provides the connection pool, postgres_pool, is from the same developer as the postgres package itself.

As far as I can see, there are already two popular packages under the hood using postgres - Victor @vlidholt with Serverpod and Kilian @schultek with Stormberry. And both wrote ORM functionality on top. Do you think it is possible in the future to create an ORM within this package?

I understand that if there were budgets and time for such a large-scale improvement, then this would have already been implemented, but perhaps, if there are no ideological objections, we could open a discussion on this topic, discuss possible approaches, because even Serverpod and Stormberry are different. And maybe it grew into something more?

**Comment by isoos** [comment]
> Do you think it is possible in the future to create an ORM within this package?

I think you (or anybody) can write an ORM on top of this package, and it should be a separate functionality. I can see why it is appealing to use an ORM, but I prefer using codegen + direct query support instead. If an ORM package needs a specific thing to support, I'm happy to add it, but I don't think this package itself should do it.

**Comment by Pingear** [comment]
What do you mean when you say codegen? Are you using any specific packages or a custom solution?

**Comment by Pingear** [comment]
Thanks a lot)
If you have the opportunity to post a more recent version to the public, that would be just great :)
I really haven’t figured it out yet, but if this package at least partially solves the problem of the boilerplate code, this is just what I need!

I don't have any questions that relate directly to the code, it was more of a discussion and not an issue, so I don't know what to do, close this issue or will you continue discussing the release of version 3 in this thread?
