### ISSUE TITLE
mappedResultsQuery() and querying views

### ISSUE THREAD

**Issue by jimmyff** [isoos/postgresql-dart#12]
Hi, not sure if this is the correct place to report issues with the postgres library, are you maintaining it now?

I've just found a little weird nuance, not sure if this is expected behaviour: 

When querying using `mappedResultsQuery(...)` if querying a postgres view, the mapped result has a blank key. I was expecting the view name?

Thanks

**Comment by dishankjindal1** [comment]
Is this addressed in v3? because i dont see this "mappedResultsQuery" in v3 directory?

**Comment by isoos** [comment]
@dishankjindal1: v3 does not support the automatic lookup of the table oids at all (== filling out table/view names and producing the double-level Map of results), and any method related to that was removed. I could be persuaded to include an oid caching utility as a separate tool in the package (PRs welcome), but not as part of the schema API or the result construction.
