### ISSUE TITLE
No stacktrace location when query fails

### ISSUE THREAD

**Issue by davidmartos96** [isoos/postgresql-dart#13]
Hello, I was wondering if there is any reason why failing queries don't have a stacktrace attached. There are times that this can be confusing when tracking errors. Is there any advice to follow in case this can be fixed in a PR?
Thank you for the library!

**Comment by isoos** [comment]
Ideally, we should have a reproducible example (e.g. local docker postgres + a test case) to debug this, and also it can be made into a permanent unit test. (e.g. one can use [this](https://pub.dev/documentation/docker_process/latest/containers_postgres/startPostgres.html) to start a local postgres docker instance with configurable setup in a test).

Are you up for creating such test case? I'm happy to review PRs and fix the code for better stack trace - once we have something to work with.

**Comment by davidmartos96** [comment]
@isoos I'll see what I can do. Thank you for the directions!
