### ISSUE TITLE
jsonDecode on Empty String

### ISSUE THREAD

**Issue by MelbourneDeveloper** [isoos/postgresql-dart#131]
I just upgraded to http ^1.1.0. It looks like it's not compatible with the Postgres SDK V1.5.0

The endpoint returns 204 with an empty body, but the code tries to parse the response.

<img width="1005" alt="image" src="https://github.com/isoos/postgresql-dart/assets/16697547/590ed6c1-f791-4b64-b80a-31252200fc61">

The problem is happening in `_parseResponse`. You can see that the body is empty string here.

<img width="1120" alt="image" src="https://github.com/isoos/postgresql-dart/assets/16697547/372dcac1-34d2-48f3-b2f5-bf29ecfc6728">

It was a query for a table with an `eq` on the ID column. The method is `PATCH`. The content length here is actually 0, so it should be hitting a different code path I would say.

**Comment by isoos** [comment]
@MelbourneDeveloper: I'm not sure if this is relevant for the `postgres` package - it doesn't depend on `package:http` and we don't deal with any HTTP request. I think this issue belongs to another package/project.

**Comment by MelbourneDeveloper** [comment]
> @MelbourneDeveloper: I'm not sure if this is relevant for the `postgres` package - it doesn't depend on `package:http` and we don't deal with any HTTP request. I think this issue belongs to another package/project.

Ah, sorry! 

I assumed the Supabase library depended on this library, but it turns out it doesn't. I will log this with Supabase. Thanks!

**Comment by MelbourneDeveloper** [comment]
@isoos 

Just to explain, the package was PostgREST. I misread the package name, and that's why this ended up here. 

I moved the issue here for people Googling this

https://github.com/PostgREST/postgrest/issues/2955
