### ISSUE TITLE
I have some issue about "conn.open() , conn.close() "

### ISSUE THREAD

**Issue by ItdaTeam** [isoos/postgresql-dart#16]
First of all, thank you for making good use of your package.

I am facing a problem while using it and would like to ask for help.

When accessing the app, the function is executed in numerous future<void> types.

conn.open() and
Repeat the conn.close() process.

In this process, when another query is executed, other functions may not be able to execute the query in the db.close() function.

example :

@override
  void initState() {
getUser(); //One
getAdmin(); //2
getother(); //3
}

1 conn.open / conn.close

okay!

but

2 conn.open / conn.close

3 conn.open / conn.close

I get an answer like this:

PostgreSQLSeverity.error : Attempting to execute query, but connection is not open.

What should I do to resolve this issue?

**Comment by isoos** [comment]
First of all, the package is intended to be used from a server application, and not a mobile app. If you are using the later, I can't really help there.

On a server app, you typically want to use a connection pool to handle the long-term lifecycle of the connections. One such package that gives you this is https://pub.dev/packages/postgres_pool

The issue you are facing are likely that you want to reuse the same connection object instance. You can call open and close only once on every connection object.
