### ISSUE TITLE
What happens if I don't "conn.close"?

### ISSUE THREAD

**Issue by ItdaTeam** [isoos/postgresql-dart#17]
Yesterday, I inquired about multi-connection open and close, but it was confirmed that all data works normally without conn.close(). What I am curious about is whether the connection pool is automatically retrieved later if the close is not done. I wonder.

I think your package is very good. However, it would be great if only the connection pool part was resolved in the process of writing a query and receiving a return in the app. Could you please help a little?

**Comment by isoos** [comment]
> What I am curious about is whether the connection pool is automatically retrieved later if the close is not done. I wonder.

A `PostgreSQLConnection` is not a connection pool, it is a single connection to the server. If you don't close it, both the client and the server would keep it alive for a while, but there is no guarantee that it will be opened forever.

> However, it would be great if only the connection pool part was resolved in the process of writing a query and receiving a return in the app.

I'm not sure: what are you trying to achieve here? Opening and closing a connection to postgres server for each new query is costly, and it is not advised, but if you wanted to, you could do something like this:
```dart
late PostgreSQLConnection conn;
try {
  conn = PostgreSQLConnection();
  await conn.open();
  await conn.query('SOMETHING');
} finally {
  await conn.close();
}
```
However, doing that for more than one query is just a waste of resources on the server, hence we keep using connection pools. It is not advised to connect from a mobile app directly, better put a server in-between, who handles both the security and the connection pooling.
