### ISSUE TITLE
Attempting to reopen a closed connection. Create a instance instead.

### ISSUE THREAD

**Issue by bubnenkoff** [isoos/postgresql-dart#21]
Hi! I get unhanded exception with text:
```
PostgreSQLSeverity.error : Attempting to reopen a
closed connection. Create a instance instead.
```

Currently I am doint (main.dart):
```
connection = PostgreSQLConnection(....); // where connection in global.dart: late PostgreSQLConnection connection;
await connection.open();  
````

No before every operation I am checking connection with:
```
  if(connection.isClosed) { 
    await connection.open();
  }
```
But does the error means that I need to do:
```
  if(connection.isClosed) { 
    connection = await connection.open();
  }
```

Or maybe something else?

**Comment by isoos** [comment]
You need to open a connection only once. What's the workload that you are doing with the connections?

**Comment by bubnenkoff** [comment]
I get issue in next function:
```
saveArchivesToDB() async {
  serviceStatus['currentTask'] = 'saveArchivesToDB';
  print('saveArchivesToDB');

  List<FTPItemModel> ftpArchives = await getListOfArchives();

  for(var archFile in ftpArchives) {
    String sql = """INSERT INTO ftp_files (...)""";
    //  print(sql);

    if(connection.isClosed) { 
       await connection.open(); 
    }

    await connection.query(sql);
  }

}
```

**Comment by isoos** [comment]
This just won't work. A `PostgreSQLConnection.isClosed` should be checked only after you have started to close a connection. Instead, you: (1) call `PostgreSQLConnection.open`, (2) use it, (3) close it. Or, use a connection pool, like `package:postgres_pool`.

**Comment by bubnenkoff** [comment]
So your are suggest to open connection before every?
```
for(var archFile in ftpArchives) {
```
and close after it?

P.S. Yes I am using your pool in another project! Big thanks for it. I figure out how to work with it.

**Comment by isoos** [comment]
> So your are suggest to open connection before every? [...] and close after it?

Yes, that's the idea. The pool just makes it easier to scale...

**Comment by bubnenkoff** [comment]
Ok, I will try now. But why connection could be closed? I do not see any exception in my code before this...

**Comment by bubnenkoff** [comment]
So I should to do something like:
```
saveArchivesToDB() async {
  serviceStatus['currentTask'] = 'saveArchivesToDB';
  print('saveArchivesToDB');

  List<FTPItemModel> ftpArchives = await getListOfArchives();

  print('Connection status: ${connection.isClosed}');
  if(connection.isClosed) { 
       await connection.open(); // open?
    }  

  for(var archFile in ftpArchives) {
    String sql = """INSERT INTO ftp_files (...)""";

    await connection.query(sql);
  }

  await connection.close(); // close 

}
````

**Comment by isoos** [comment]
Instead of this:
```
if(connection.isClosed) { 
       await connection.open(); // open?
    }  
```

Why don't you do:
```
  final connection = PostgreSQLConnection(/* something */);
  await connection.open();
  try {
    for(var archFile in ftpArchives) {
      String sql = """INSERT INTO ftp_files (...)""";
      await connection.query(sql);
    }
  } finally {
    await connection.close();
  }
```

**Comment by bubnenkoff** [comment]
Thanks! But why connection could be closed? it's just interesting why I am facing with this error? I am got error above only after 5-10 minutes of app work.

**Comment by isoos** [comment]
To be honest, I have no idea, e.g. it could be the server closing the connection. I only use the pool, which takes care of most of these lifecycle glitches. Also note: `isClosed` (or the events that lead up to it) may have a bug...

**Comment by isoos** [comment]
Closing as old/obsolete issue. The new version may have similar issue, right now the `Pool` implementation is included in the package.
