### ISSUE TITLE
[Bug] Easy to live lock the db connection with bad transaction

### ISSUE THREAD

**Issue by mchandler-plato** [isoos/postgresql-dart#229]
I recently encountered a very hard to debug code bug introduced by a cleanup where inside a transaction the wrong db object was used to make a query with a single db connection and the await never returned and all future queries on the db object hanged too. 

```
  final db = PgPool(endpoint, settings: PgPoolSettings()
      ..concurrency = 1);

  await db.runTx((c) async {
    await db.execute("select * from abcd limit 1", timeoutInSeconds: 5);
  });
```

What i would expect in this case is that the execute would timeout and cancel the transaction allow things to return to normal with runTx throwing too.

The proper version of the above should be this and works just fine: 
```
  final db = PgPool(endpoint, settings: PgPoolSettings()
      ..concurrency = 1);

  await db.runTx((c) async {
    await c.execute("select * from abcd limit 1", timeoutInSeconds: 5);
  });
```

**Comment by isoos** [comment]
@mchandler-plato: you seem to be using an older version of the package. the latest HEAD now seems to fixed this: #230

**Comment by mchandler-plato** [comment]
Im on the following version, let me try updating though and retest.
```
  postgres: ^2.6.1
  postgres_pool: ^2.1.6
```

**Comment by isoos** [comment]
Ah, hm, that version may not get a fix anytime soon, if ever. We are working on getting the `3.0.0` release out (which will likely make `postgres_pool` deprecated/discontinued, as we have now the Pool integrated tightly with the package).

**Comment by mchandler-plato** [comment]
Cant wait till its out to update to v3 and use it. Also love that you made a test for this case too. Thanks
