### ISSUE TITLE
Use :parameter instead of @parameter

### ISSUE THREAD

**Issue by xvrh** [isoos/postgresql-dart#248]
This library uses `@id` for query parameters (like `where id=@id`)

But this syntax is not recognised by default in IntelliJ.
<img width="603" alt="Screenshot 2023-11-15 at 15 03 32" src="https://github.com/isoos/postgresql-dart/assets/5110923/a013412b-2a01-4e7b-9e14-2440b6e81680">

In IntelliJ the syntax `:id` works very well. It's recognised and you can even just run the query directly and the IDE will show a popup to pass the parameter.
<img width="606" alt="Screenshot 2023-11-15 at 15 07 06" src="https://github.com/isoos/postgresql-dart/assets/5110923/454b7b9a-58bf-4e9b-9ac6-8b3759ef4048">

<img width="610" alt="Screenshot 2023-11-15 at 15 08 20" src="https://github.com/isoos/postgresql-dart/assets/5110923/33efbfc1-c7c4-4d84-9892-771e15e745e5">

Maybe it's just a settings to configure the `@` somewhere in the IDE. But still I wonder how the `@` was chosen and if `:` is not more common?

**Comment by isoos** [comment]
I think you may use it with [`Sql.named`](https://pub.dev/documentation/postgres/latest/postgres/Sql/Sql.named.html), it has a `substitution` parameter, which could be set to `:`. Could you please check that?

**Comment by xvrh** [comment]
Thanks @isoos . `Sql.named('select :id', substitution: ':')` is working.

**Comment by dishankjindal1** [comment]
This issue is not an issue? Just a IDE configuration KT session?
cc: @xvrh

**Comment by isoos** [comment]
@dishankjindal1: The package supports multiple query parameter style, the default being the raw format that Postgresql expects. I don't use IntelliJ, but apparently if you use `Sql.named('select :id', substitution: ':')` it works in IntelliJ (and it works in `package:postgres`. Let us know if we could make any other changes to make your life better, but right now I consider this working and not an issue.

**Comment by xvrh** [comment]
I agree this is not a bug.
This is more a request to change the default substitution character to `:`.
The fact that IntelliJ uses `:` for postgres indicates to me that is more common. But I admit I cannot find any other evidence to back my intuition. So I'll close this ticket :-)

**Comment by isoos** [comment]
> This is more a request to change the default substitution character to :.

This is a though call: the 1.x and 2.x of this package used only `@` as substitution, and it is likely that we should stick with that for the time being in 3.x for people migrating. `Sql.colonNamed` or `Sql.colon` could be added if that helps this use case. It would be nice to see why IntelliJ does the `:` though, and what others are using...
