### ISSUE TITLE
Migration for PostgreSQLExecutionContext.cancelTransaction()?

### ISSUE THREAD

**Issue by Ri-car-do-1989** [isoos/postgresql-dart#249]
In the old version, I used this:

```
await connection.runTx((ctx) async {
   //...Do Stuff
   if(condition){
     ctx.cancelTransaction();
   }
}
```

With the new version, I found no cancelTransaction method for Session. So how to migrate it (Or: how to cancel a transaction based on a condition)?

**Comment by isoos** [comment]
Good point, this may seems to be an oversight. The quick-to-unblock way is to throw an exception which you catch outside, but I shall prepare a PR for this soon.
