### ISSUE TITLE
How to use new execute API?

### ISSUE THREAD

**Issue by Tienisto** [isoos/postgresql-dart#251]
Hello, congratulations for the new 3.0 release. I really like that it has support for pooling!

During migration, I don't quite understand how `Session.execute` work. Due to overloading of the method signature, and no examples provided in the README / documentation, it is not easy to know how to use the API.

From my understanding, I would write the following:

```dart
await _connection.execute(
    'INSERT INTO my_table (user_id, email) VALUES (@userId, @email)',
    parameters: {
    'userId': 123,
    'email': 'user@example.com',
  },
);
```

Since `Object` is not very type-safe, I also like to have `executeString` or `executeSql` for more type-safety, if the parameter type is depending on `Sql` or `String`.

**Comment by Tienisto** [comment]
Nevermind, I missed `Sql.named`

**Comment by isoos** [comment]
`execute` accepts `String` but treats it as if it were raw/unescaped `Sql(value)`

In your case, you want to have the named variable substitution, and you should use `Sql.named('INSERT INTO my_table (user_id, email) VALUES (@userId, @email)',)` instead

**Comment by isoos** [comment]
Please feel free to expand on the dartdoc and/or readme parts if something is not trivial, we are probably blind to these annoying changes as we were looking at the new API way too long now :)
