### ISSUE TITLE
"Instance of 'UndecodedBytes'" when getting the result of a function

### ISSUE THREAD

**Issue by ronspe** [isoos/postgresql-dart#257]
I'm using version 3.0.1
When I get the results from a simple query the results are fine.
e.g: 
`var conn = await openDatabaseConnection();
  var results = await conn.execute('SELECT * from table1);`

However when I try to get the results from a function I get "Instance of 'UndecodedBytes' " for each part of the results. e.g.:
`var conn = await openDatabaseConnection();
  var results = await conn.execute('SELECT get_t1_data(););`

This is a simplified version of the function:
`CREATE OR REPLACE FUNCTION public.get_t1_data()
 RETURNS TABLE(id integer, name text, description text)
 LANGUAGE plpgsql
AS $function$
      BEGIN
             RETURN QUERY
             SELECT t1.id, t1.name, t1.description
               FROM public.table1 AS t1;
       END
   $function$
;
`

How can I resolve the "Instance of 'UndecodedBytes' "?

**Comment by isoos** [comment]
@ronspe: I'm not sure how the `SELECT get_t2_data()` works, but the test in #258 uses `SELECT * from get_t1_data()` and it works as expected. Is this something that works in other context?

**Comment by ronspe** [comment]
Hi @isoos,

Thank you for your quick reply! You are right, I works fine with SELECT * from function(). 

I checked the Postgres documentation and they did tell me that this is the correct way for functions that return a table. Sorry for not reading that part of the documentation. 

I assumed the problem was in my configuration in Dart because it does work fine  when I run the query in DBeaver 23.2.1 So that tripped me up...
See screenshot:
![image](https://github.com/isoos/postgresql-dart/assets/44189214/f6ca8384-1c0b-48df-b0af-9c86a77abf06)

Thanks for your help!

**Comment by isoos** [comment]
@ronspe: sounds good :) though, I'm not as deep in the postgres spec as I should be, so if this (or a related feature) is something we should support, please report it.
