### ISSUE TITLE
Retiere / archive stablekernel/postgresql-dart 

### ISSUE THREAD

**Issue by Gustl22** [isoos/postgresql-dart#26]
Hi @isoos,

I don't know the reasons, and also don't want to induce any conflicts, but wouldn't it make sense to retire/archive the repo https://github.com/stablekernel/postgresql-dart and link them to this one?

Obviously the main repo isn't intended to be updated any more, or is it? But I think it leads to much confusion, if there aren't any hinds where to continue. Or much worse, users think it's not worth using the package, because the repo doesn't seem to be updated any more. Therefore popularity might be harmed and can loose important contributions.

Sorry if you don't have influence on this, and big thanks for maintaining anyways! Best regards!

**Comment by isoos** [comment]
@Gustl22: good point, I've requested it to detach this repo. Unfortunately, I don't have full access rights to `stablekernel/postgresql-dart`, so I can't archive it...

**Comment by isoos** [comment]
This repo has been detached, closing the issue for now, as I can't really do much about the ex-parent.
