### ISSUE TITLE
Please document @Deprecated classes and methods like PostgreSQLExecutionContext, etc.

### ISSUE THREAD

**Issue by tgrushka** [isoos/postgresql-dart#265]
I would like to migrate to V3 but it is really difficult to guess what changes need to be made.

Specifically, the following deprecation comments:
```dart
@Deprecated('Do not use v2 API, will be removed in next release.')
```
are generic and unhelpful.

One reason I love the Dart language is because most developers are very helpful with their deprecation messages and state exactly what to use in place, and those new classes have good documentation on how to use them. I feel it would be important for the reputation of this library and also the Dart community to ensure that popular and useful libraries like this one have very good documentation, because no one can read the minds of the experts who develop the libraries. We just want a low friction to use them and not have to worry about their internals. If something is not feature complete, please just state that and the planned syntax or a link to the issue/roadmap item in the repo to follow that feature, or at least in the doc comments for the deprecated class. Thank you.

**Comment by isoos** [comment]
@tgrushka: I feel the pain. At the same time we have spent months already with the new API, and we are mostly blind if this is a breeze to upgrade or a long fight. I'd encourage you to look at the examples, I think you'll find most uses there:
https://pub.dev/packages/postgres/example

If needed you can also look into the implementation of how the old API translates to the new one:
https://github.com/isoos/postgresql-dart/blob/master/lib/src/v2/v2_v3_delegate.dart

I'm also happy to accept PRs with any guide that helps others to migrate the API.

**Comment by isoos** [comment]
The v2 API has been removed recently, the focus is now on new features with the v3.
