### ISSUE TITLE
Issue with key word like in select query

### ISSUE THREAD

**Issue by charlesHenryPATARD** [isoos/postgresql-dart#27]
Hi,

I try to create a query with a select and like in where clause. Like this : 

`List<List<dynamic>> queryRowsList = await connection.query(
        "SELECT id, name, description FROM projects WHERE LOWER(name) like LOWER('%@name%') order by name",
        substitutionValues: {"name": name});`
But when I execute the query in unit test I've got this error : 

` PostgreSQLSeverity.error 08P01: bind message supplies 1 parameters, but prepared statement "000000000000" requires 0 
  package:postgres/src/connection.dart 453:18                            _PostgreSQLExecutionContextMixin._query
  package:postgres/src/connection.dart 427:7                             _PostgreSQLExecutionContextMixin.query
  package:wiki_pages_converter/utilities/db/projects_queries.dart 25:58  ProjectsQueries.readProjects
  test/model/queries_test.dart 33:35                                     main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                             _Completer.completeError
  package:postgres/src/query.dart 172:17                                 Query.completeError
  package:postgres/src/connection_fsm.dart 281:15                        _PostgreSQLConnectionStateBusy.onMessage
  package:postgres/src/connection.dart 286:47                            PostgreSQLConnection._readData
  ===== asynchronous gap ===========================
  dart:io                                                                _Socket.listen
  package:postgres/src/connection.dart 171:16                            PostgreSQLConnection.open
  ===== asynchronous gap ===========================
  dart:async                                                             _asyncThenWrapperHelper
  package:wiki_pages_converter/utilities/db_connect.dart 22:24           DbConnect.connectToDB
  test/model/queries_test.dart 25:57                                     main.<fn>.<fn>
  test/model/queries_test.dart 21:9                                      main.<fn>.<fn>`

It's seems that LOWER('%@name%') is not correctly understood. If try to write  LOWER(@name) it's works. But it's not that I want.
If I execute the query in DBeaver and replace the @name by real text everything works.

Best regards.

**Comment by charlesHenryPATARD** [comment]
I fixed my issue with this query : 

`List<List<dynamic>> queryRowsList = await connection.query(
        "SELECT id, name, description "
        "FROM projects "
        "WHERE LOWER(name) like LOWER('%"+name+"%') order by name");`

The reason is that the substitutionValues: {"name": name} don't work with like key word. We need to use "real dart variable".

**Comment by isoos** [comment]
Your fix is unfortunately an attack vector for SQL injection attacks, so I'd rather have a different solution.
My first intuition is that 'LIKE LOWER(@name)` with `substitutionValues: {'name': '%$name%'})` should work without changing the substitution code in the package.

**Comment by isoos** [comment]
Please try the above, and if it does not work, we should probably figure out how it should work (`substituter.dart` and `interpolation_test.dart`).

**Comment by charlesHenryPATARD** [comment]
Hi @isoos,

It's works thanks a lot. 
I've got an other issue with a query with a clause **WHERE** clause and a **in ()**.

The query is : 

`"SELECT id, text "
        "FROM wiki_contents "
        "WHERE id in (@idList) order by id",
        substitutionValues: {'idList':idListStr}
`
idListStr = '300',400',...

Can you tell me how to write it correctly ? Thanks

**Comment by isoos** [comment]
Oh, that's a bit different issue. The crude workaround is to use `... WHERE id IN (${List.generate(idList.length, (i) => '@p$i').join(', ')}) ORDER BY id`, and generate a `substitutionValues` `Map` for each `pX` -> `idList[X]` pair.

Ideally this could be (a) detected from the query string, but that opens up a lot of possibility for bugs, or (b) we could add a new List-based type that could be used for cases like that, and would do the above escaping transparently.

**Comment by charlesHenryPATARD** [comment]
Hi,

Thanks for your answer. I understand that the (b) solution is the best. Do you will code this solution ?

I will try the (a) solution at the end of the week.

**Comment by isoos** [comment]
I believe the v3 API has better support for this.
