### ISSUE TITLE
version 3.0.3 | Error when connecting to the database 

### ISSUE THREAD

**Issue by semicolon-real** [isoos/postgresql-dart#270]
**There is no problem in version 2.6.3**

**Error:**
```
Asynchronous error
Bad state: Future already completed
dart:async                                      _Completer.completeError
package:postgres/src/v3/connection.dart 254:34  PgConnectionImplementation._connect.<fn>
```

**Comment by isoos** [comment]
@semicolon-real: what is the code that you are calling the connection from?

**Comment by semicolon-real** [comment]
The connection is created inside the runQuery
`      _conn ??= await Connection.open(_endpoint,settings: _settings);`

Full source
```
import 'dart:developer';
import 'dart:io';

import 'package:dart_frog/dart_frog.dart';
import 'package:fitkey_server/core/app_const.dart';
import 'package:fitkey_server/core/exception_manager/custom_exc/db_service_exc.dart';
import 'package:postgres/postgres.dart';

class DBService {

  factory DBService() => _instance;
  DBService._internal();
  static final DBService _instance = DBService._internal();

  final Endpoint _endpoint = Endpoint(
    host: AppConst.dbHost,
    database: AppConst.dbName,
    username: AppConst.dbUserName,
    password: AppConst.dbPassword,
  );

  final ConnectionSettings _settings = const ConnectionSettings(
    connectTimeout: Duration(seconds: 10),
    queryTimeout: Duration(seconds: 5),
  );

  Connection? _conn;

  Future<Result> runQuery(String fmtString, {Map<String, dynamic>? parameters}) async {
    try{
      _conn ??= await Connection.open(_endpoint,settings: _settings);
      return await _conn!.execute(fmtString, parameters: parameters);
    } on SocketException {
      throw DBServiceExc(DBServiceExcEnum.serviceUnavailable);
    } catch (e) {
      log('$e\n$fmtString');
      throw DBServiceExc(DBServiceExcEnum.unknownException);
    }
  }

  Middleware dbProvider() {
    return provider<DBService>((context) => DBService());
  }
  
}
```

**Comment by isoos** [comment]
`connection.dart 254:34` indicates https://github.com/isoos/postgresql-dart/blob/master/lib/src/v3/connection.dart#L254-L255 which seems to be an SSL connection error. I think you may need to set the `sslMode` on the connection settings: https://pub.dev/documentation/postgres/latest/postgres/ConnectionSettings/sslMode.html

But I also need to fix the linked code to not fail an already completed `Completer`.

**Comment by semicolon-real** [comment]
I tried all the options 'disable, require, verifyFull'
The problem persists

**Comment by isoos** [comment]
1. what/where is the server you are connecting to?
2. can you try the latest HEAD on github?

**Comment by semicolon-real** [comment]
I got the latest version from GitHub and added its path
```
  postgres:
    path: ./packages/postgresql-dart
```

I use PostgreSQL version 16.1 on Windows as localhost with default port
The project is Dart Frog

**Comment by semicolon-real** [comment]
Now I get this error
Server does not support SSL, but it was required.
To fix this problem, changes should be made in PostgreSQL?

**Comment by semicolon-real** [comment]
it was my mistake
i used this option and the problem was solved
`sslMode: SslMode.disable,`

**Comment by isoos** [comment]
Thanks for debugging and getting to the core of the issue. I hope the fix should be helpful for future users.

One note though: without SSL, only local/VPN servers should be used, otherwise your credentials are in the cleartext over the network.
