### ISSUE TITLE
Port number is incorrect automatically

### ISSUE THREAD

**Issue by shinriyo** [isoos/postgresql-dart#277]
I wrote the code below.

```
                final conn = await Connection.open(Endpoint(
                  host: 'db.srubwrrvsvnxdktwmuxj.supabase.co',
                  database: 'postgres',
                  username: 'postgres',
                  password: '[my password]',
                  port: 5432,
                ));
                print("onTap called.");
                final result = await conn.execute("SELECT * from Post");
```

but it says using 64990 port.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = db.srubwrrvsvnxdktwmuxj.supabase.co, port = 64990
```

I want to use `5432` one.

**Comment by isoos** [comment]
The port reported is usually the local port, the socket tries to connect to the correct remote port.

This issue looks like an android permission issue. Note: even if you resolve the permission issue, it is not advised to store database credentials in your mobile app.

**Comment by shinriyo** [comment]
I use it on an iPhone simulator.
Does the module work for simulator?

**Comment by isoos** [comment]
> I use it on an iPhone simulator.
> Does the module work for simulator?

I have no knowledge about iPhone development. But the recommendation still applies: it is not advised to store database credentials in your mobile app. (or use them to connect to a database directly)

**Comment by shinriyo** [comment]
I use it by myself. I need not to be concerned about security problems.
By the way, how can I change the port number?

**Comment by isoos** [comment]
> By the way, how can I change the port number?

I think you are using the right port, it may be an ios permission issue.

**Comment by isoos** [comment]
Closing as not actionable.
