### ISSUE TITLE
Can't connect to cockroach labs -- ServerException (Severity.error null: Refused to send clear text password to server

### ISSUE THREAD

**Issue by rogersm-uwosh** [isoos/postgresql-dart#282]
I have got the simplest of all possible Dart programs, and am trying to connect to cockroach labs. The program crashes on the first line with a complaint about a clear text password, even though I'm using SslMode.require. 

Any help would be most welcome!

`void main() async {
  final conn = await Connection.open(
    Endpoint(
      port: 26257,
      host: 'somethingcockroachlabs.cloud',
      database: 'someday',
      username: 'someuser',
      password: 'some password',
    ),
    // The postgres server hosted locally doesn't have SSL by default. If you're
    // accessing a postgres server over the Internet, the server should support
    // SSL and you should swap out the mode with `SslMode.verifyFull`.
    settings: ConnectionSettings(sslMode: SslMode.require),
  );
  print('has connection!');
`

**Comment by isoos** [comment]
Not sure: do you use an SSL port that the server exposes? Otherwise use `SslMode.disable`:

```
disable → const SslMode
No SSL is used, implies that password may be sent as plaintext.
```

**Comment by rogersm-uwosh** [comment]
Thanks for getting back to me. If I use verifyFull I get the error that it doesn’t like clear passwords; and if I use SslMode.disable I get an error 08C00: server requires encryption.

Michael

On Jan 23, 2024, at 2:37 PM, István Soós ***@***.***> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Not sure: do you use an SSL port that the server exposes? Otherwise use SslMode.disable:

disable → const SslMode
No SSL is used, implies that password may be sent as plaintext.

**Comment by isoos** [comment]
Which server is this and how do you start it?

**Comment by rogersm-uwosh** [comment]
It’s a CockroachDB instance on CockroachLabs, so the server’s always on.

Michael

On Jan 23, 2024, at 2:44 PM, István Soós ***@***.***> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Which server is this and how do you start it?

**Comment by isoos** [comment]
I'm not sure, but maybe they are also using some kind of client-side certificate that needs to be included?

**Comment by isoos** [comment]
One intermedia workaround could be to use `pgbouncer` (or other postgres proxy) as a locally run proxy that connects to the cockroachdb cloud.

**Comment by rogersm-uwosh** [comment]
So, I modified my code to include a reference to the root.crt that I downloaded from Cockroachlabs, but this is giving me the same error - Refused to send clear text password to server.

```
 SecurityContext context = SecurityContext();
// The path to the trusted root certificate file
  context.setTrustedCertificates('/Users/me/.postgresql/root.crt');

  final conn = await Connection.open(
    Endpoint(
      port: 26257,
      host: 'aserver.cockroachlabs.cloud',
      database: 'defaultdb',
      username: 'auser',
      password: 'apassword',
    ),
    // The postgres server hosted locally doesn't have SSL by default. If you're
    // accessing a postgres server over the Internet, the server should support
    // SSL and you should swap out the mode with `SslMode.verifyFull`.
    settings: ConnectionSettings(
        sslMode: SslMode.verifyFull, securityContext: context),
  );
  print('has connection!');
```

**Comment by isoos** [comment]
@rogersm-uwosh: I'm a bit surprised by this. Can you create a fork of the package and modify the following line?
https://github.com/isoos/postgresql-dart/blob/master/lib/postgres.dart#L418
```
bool get allowCleartextPassword => true;
```
I'm wondering if we are too strict about something.

**Comment by rogersm-uwosh** [comment]
I'll give it a try and report back!

**Comment by rogersm-uwosh** [comment]
First, in case I forget to say so, I really appreciate your help!

 I modified my file spec to be:

`dependencies:
  postgres:
    git:
      url: https://github.com/myuserid/postgresql-dart.git
  # path: ^1.8.0`
  
 where line 418 now reads:
  
    bool get allowCleartextPassword => this == true;
    
    But I keep getting the same error : ServerException (Severity.error null: Refused to send clear text password to server)
    
    
  SecurityContext context = SecurityContext();
  context.setTrustedCertificates('/Users/me/.postgresql/root.crt');

  final conn = await Connection.open(
    Endpoint(
      port: 26257,
      host: 'adatabase.cockroachlabs.cloud',
      database: 'defaultdb',
      username: 'auser',
      password: 'apassword',
    ),
       settings: ConnectionSettings(
        sslMode: SslMode.verifyFull, securityContext: context),
  );
  print('has connection!');

**Comment by isoos** [comment]
Note: I wrote `allowCleartextPassword => true;` while you did `this == true` (which is always `false`).

**Comment by rogersm-uwosh** [comment]
That worked! And after having spending 20 minutes watching videos on NoSQL, let me just say how happy I am to see that 😀.

Michael

On Jan 23, 2024, at 5:08 PM, István Soós ***@***.***> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Note: I wrote allowCleartextPassword => true; while you did this == true (which is always false).

**Comment by isoos** [comment]
@simolus3: what do you think about not blocking the cleartext password in such cases? Maybe another explicit override if we want to make sure the user knows what they are doing?

**Comment by rogersm-uwosh** [comment]
So is the problem really with CockroachLabs? They do provide a connection string that works (in some situations), is it possible to just send a connection string like you do in some other APIs, e.g.,

"postgresql://auser:<ENTER-SQL-USER-PASSWORD>@aserver.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full" ?

**Comment by simolus3** [comment]
> what do you think about not blocking the cleartext password in such cases?

I think this is simply a bug in the implementation, not something that would need a special option. We're not sending passwords in cleartext (because there's an SSL connection), so the package should not refuse to send the password.

> is it possible to just send a connection string like one might do in some other APIs

It's not, but I've thought about this as well and it might be something worth exploring.

**Comment by isoos** [comment]
Published fix in the latest version.
