### ISSUE TITLE
Possible memory leak by leaving an open connection

### ISSUE THREAD

**Issue by lslv1243** [isoos/postgresql-dart#29]
Hello, I want to share something that I found recently about a possible memory leak in the library.

I am currently using the lib in production and have been suffering with memory leak in the server for a while. A thing I had been doing in the server was leaving a connection open to the database. I have investigated various pieces of the code of the server and could not find the source of the leak. One day an idea came to my mind: what if leaving a connection open to the database is the problem? Then I made a change to my code, instead of leaving the connection open through the whole lifetime of the application, I renew it after every 1 hour. And the problem with leaking memory seems to have gone away.

![image](https://user-images.githubusercontent.com/23214418/154371527-b71a50d8-53ac-4e86-833c-0c78c5b87f56.png)

In the graph, the region named "Old server", is a version of the server with everything the same except for the change of renewing the connection every 1 hour. And the region named "New server" is the new version.

I brought this subject to raise some questions: Are you currently using this library in production? Are you experiencing the same increase in memory usage?

If this problem affects more people I would be really happy to dig deeper and try to find out the problem and make the fix.

**Comment by isoos** [comment]
>  Are you currently using this library in production? Are you experiencing the same increase in memory usage?

Yes, I have experienced similar thing, and my conclusion was similar: I have developed `package:postgres_pool` to handle the auto-reconnection and other pooling features.

When I brought it up with the original developers, they have claimed that they haven't experienced similar issues, so I thought it may have been my setup (which was using 90% CockroachDB and 10% Postgresql, so it may have been a difference in the server). Since I've taken over maintenance of the library, I'm planning to eventually merge the pooling features with the core connection handling, but I haven't had much time to actually do it.

> If this problem affects more people I would be really happy to dig deeper and try to find out the problem and make the fix.

Please do, I'd be happy to help reviewing and/or fixing it.

**Comment by zambetpentru** [comment]
When I do say 100k inserts (I know this is not the best for performance) the memory of the postgres server increases. In the past I came across this so I avoided using the pool and sent 30k inserts in a batch closing the connection in between. Is there something I'm missing to release the memory after the inserts? *They are not being done in a transaction and appear immediately in the table.

**Comment by isoos** [comment]
@zambetpentru: the new v3 API has the `Pool` integrated as part of the package. I've experienced the same overload on the server before, and the new API has a few knobs that can be used to limit the effect of it:
https://pub.dev/documentation/postgres/latest/postgres/PoolSettings-class.html

- `maxConnectionAge` - The maximum duration a connection is kept open. New sessions won't be scheduled after this limit is reached.
- `maxQueryCount` - The maximum number of queries to be run on a connection. New sessions won't be scheduled after this limit is reached.
- `maxSessionUse` - The maximum duration a connection is used by sessions. New sessions won't be scheduled after this limit is reached.

If you are using the connections through the `Pool` interface, it will auto-close and create new connections after any of these limits is reached.

**Comment by zambetpentru** [comment]
Yes, will be interesting to move to the new API when I get a chance.   Thank you for your reply, maxQueryCount is exactly what I needed to adjust on pgPool to avoid the Postgresql memory growing out of bounds and just tested it now.

**Comment by isoos** [comment]
Closing as the v3 api has been launched for a while now.
