### ISSUE TITLE
Expose GenericType encoding and decoding

### ISSUE THREAD

**Issue by wolframm** [isoos/postgresql-dart#293]
I am implementing `numrange` as custom type. It would be great if I could use the existing `PostgresBinaryEncoder` and `PostgresBinaryDecoder` to convert the lower/upper range value. However, it does not seem possible as the relevant parts of the library are not exposed.

To encode:
```
final input = EncodeInput('123.456',Utf8Codec());
final Uint8List encoded = Type.numeric.encode(input);
```
To decode:
```
final input = DecodeInput([3,21,84,0,...],true,Utf8Codec(),TypeRegistry());
final String decoded = Type.numeric.decode(input);
```
Alternatively, directly exposing `PostgresBinaryEncoder` and `PostgresBinaryDecoder` plus `EncodeInput` and `EncodeInput` would also work.

Could you expose the relevant parts of the library or is there another way to this?

**Comment by wolframm** [comment]
Or perhaps I should add `Type.numrange` directly to the library?

**Comment by isoos** [comment]
> Or perhaps I should add Type.numrange directly to the library?

I was to suggest the same. Anything that is an official type should be handled as such (eventually):
https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-BUILTIN

Would you be interested in contributing? You may follow the current pattern of encode/decode, or create a separate class for it too (long term we want to have separate ones, but doesn't matter much right now).

**Comment by wolframm** [comment]
I agree. Adding to `postgresql-dart` is best.

I've already written encoders/decoders for the geometric types, `int4range` and `int8range`. So I could complete the set of builtin range types and then make a pull request. 

I also would like to add `time` as Dart `int` with a check in the encoder that the value is not negative and not larger than `24:00:00.000000`. Would that be okay?

I would use the current encode/decode pattern.

I haven't really looked into the test folder yet, but I assume I should add tests for new `Type`s in `decode_test.dart` and `encoding_test.dart`?

**Comment by isoos** [comment]
> I also would like to add time as Dart int with a check in the encoder that the value is not negative and not larger than 24:00:00.000000. Would that be okay?

Similarly to `Interval` this could be a custom `Time` type. Users would use the `int` to convert to hours/minutes... anyway, we should support that as we know about the actual intent of the `int`.

**Comment by isoos** [comment]
> I haven't really looked into the test folder yet, but I assume I should add tests for new Types in decode_test.dart and encoding_test.dart?

Yeah, that can work, or you could just create a `test/type/numrange_test.dart` or similar file (long term I want to reach something like that).
