### ISSUE TITLE
Multiple asynchronous requests through connection Pool breaks transaction integrity.

### ISSUE THREAD

**Issue by SandPod** [isoos/postgresql-dart#297]
## Description

If multiple asynchronous requests are performed on a connection pool it seems like the integrity for transactions breaks.

When testing I noticed that transactions did not seem to be performed as atomic actions and multiple transactions were executed in concurrently, that is access and modify the same rows concurrently.

Enclosed are tests that isolate the issue as close as possible. If only one asynchronous request is performed and then awaited the issues is not observed. There seems to be something happening in the connection pool when multiple requests are triggered concurrently.

I'm a maintainer for https://github.com/serverpod/serverpod and use this library internally. We are working on migrating to `^3.0.0` but would love to see this fixed in the standalone `postgres_pool` library if possible, since it has it's own release maybe it would be possible to patch it there. I would suspect it is a shared issue since it is present in both the standalone library and in `^3.0.0`.

## Expected behavior
Multiple asynchronous request should not influence the execution integrity of transactions.

## Actual behavior
Asynchronous requests through the same connection pool breaks the integrity of transactions.

## Tests

Following tests assume that there exists a database with the following table definition:
```sql
CREATE TABLE "simple_data" (
    "id" serial PRIMARY KEY,
    "num" integer NOT NULL
);
```

### Library version 3.0.8

Pubspec used.
```yaml
name: postgres_legacy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  postgres: 3.0.8 

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
```

<details><summary><h4>Passing test for direct connection</h4></summary>

```dart
import 'package:postgres/postgres.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  late Connection connection;

  setUpAll(() async {
    connection = await Connection.open(
      Endpoint(
        host: 'localhost',
        port: 5432,
        database: 'serverpod_test',
        username: 'postgres',
        password: 'password',
      ),
      settings: ConnectionSettings(sslMode: SslMode.disable),
    );
  });

  tearDownAll(() async {
    await connection.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await connection.execute('INSERT INTO $tableName (num) VALUES (1);');

    var first = connection.execute('SELECT 1;');
    var second = connection.execute('SELECT 1;');

    await Future.wait([first, second]);

    var firstTransaction = connection.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = connection.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```

</details>

<details><summary><h4>Failing test for pool connection</h4></summary>

```dart
import 'package:postgres/postgres.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  var poolSettings = PoolSettings(
    maxConnectionCount: 10,
    queryTimeout: const Duration(minutes: 1),
    sslMode: SslMode.disable,
  );
  var pgPool = Pool.withEndpoints(
    [
      Endpoint(
        host: 'localhost',
        port: 5432,
        database: 'serverpod_test',
        username: 'postgres',
        password: 'password',
      )
    ],
    settings: poolSettings,
  );

  tearDownAll(() async {
    await pgPool.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await pgPool.execute('INSERT INTO $tableName (num) VALUES (1);');

    var first = pgPool.execute('SELECT 1;');
    var second = pgPool.execute('SELECT 1;');

    await Future.wait([first, second]);

    var firstTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```

</details>

### Library version 2.6.3 and 2.6.1+1
Pubspec used.

```yaml
name: postgres_legacy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  postgres: 2.6.3
  postgres_pool: "2.1.6+1"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

```
<details><summary><h4>Passing test for direct connection</h4></summary>

```dart
import 'package:postgres/postgres.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  var connection = PostgreSQLConnection(
    'localhost',
    5432,
    'serverpod_test',
    username: 'postgres',
    password: 'password',
  );

  setUpAll(() async {
    await connection.open();
  });
  tearDownAll(() async {
    await connection.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await connection.query('INSERT INTO $tableName (num) VALUES (1);');

    var first = connection.query('SELECT 1;');
    var second = connection.query('SELECT 1;');

    await Future.wait([first, second]);

    var firstTransaction = connection.transaction((ctx) async {
      var result = await ctx.query('SELECT * FROM $tableName;');
      await ctx.query('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = connection.transaction((ctx) async {
      var result = await ctx.query('SELECT * FROM $tableName;');
      await ctx.query('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```

</details>

<details><summary><h4>Failing test for pool connection</h4></summary>

```dart
import 'package:postgres_pool/postgres_pool.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  var poolSettings = PgPoolSettings();
  poolSettings.concurrency = 10;
  poolSettings.queryTimeout = const Duration(minutes: 1);
  var pgPool = PgPool(
    PgEndpoint(
      host: 'localhost',
      port: 5432,
      database: 'serverpod_test',
      username: 'postgres',
      password: 'password',
    ),
    settings: poolSettings,
  );

  tearDownAll(() async {
    await pgPool.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await pgPool.query('INSERT INTO $tableName (num) VALUES (1);');

    var first = pgPool.query('SELECT 1;');
    var second = pgPool.query('SELECT 1;');

    await Future.wait([first, second]);

    var firstTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.query('SELECT * FROM $tableName;');
      await ctx.query('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.query('SELECT * FROM $tableName;');
      await ctx.query('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```
</details>

**Comment by isoos** [comment]
Note: I don't see any transaction isolation being used here, assuming that it will use the default posgres isolation levels, which is read committed. One improvement of the 3.0 API is the setting that can be used:
https://pub.dev/documentation/postgres/latest/postgres/TransactionSettings/isolationLevel.html

Of course in the end it will only execute a statement on the session:
https://www.postgresql.org/docs/current/transaction-iso.html

Also note: the test here seems to be indeterministic, see in comparison the package's transaction isolation tests with completers to control for race conditions:
https://github.com/isoos/postgresql-dart/blob/master/test/transaction_test.dart#L727

All-in-all: I think 3.0 behaves as one would expect in terms of transaction isolations, unless I'm missing some obvious here.

**Comment by SandPod** [comment]
I might be missing something here as well. I'll make sure to read the links provided.

But this test modification might help clarify the behavior I find strange. Please let me know if this is to be expected.

If I modify the failing connection pool 3.0 test into only performing a single query before the transactions that is awaited the test passes and the transaction integrity is intact.

Therefore, my conclusion was that there is something that breaks in the pool when multiple queries are instantiated asynchronously that is not recoverable for the connection pool.

Modified passing test:

```
import 'package:postgres/postgres.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  late Connection connection;

  setUpAll(() async {
    connection = await Connection.open(
      Endpoint(
        host: 'localhost',
        port: 5432,
        database: 'serverpod_test',
        username: 'postgres',
        password: 'password',
      ),
      settings: ConnectionSettings(sslMode: SslMode.disable),
    );
  });

  tearDownAll(() async {
    await connection.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await connection.execute('INSERT INTO $tableName (num) VALUES (1);');

    var first = connection.execute('SELECT 1;');
    // var second = connection.execute('SELECT 1;');

    // await Future.wait([first, second]);
    await Future.wait([first]);

    var firstTransaction = connection.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = connection.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```

**Comment by SandPod** [comment]
I might be missing something here as well. I'll make sure to read the links provided.

But this test modification might help clarify the behavior I find strange. Please let me know if this is to be expected.

If I modify the failing connection pool 3.0 test into only performing a single query before the transactions that is awaited the test passes and the transaction integrity is intact.

Therefore, my conclusion was that there is something that breaks in the pool when multiple queries are instantiated asynchronously that is not recoverable for the connection pool.

Modified passing test:

```
import 'package:postgres/postgres.dart';
import 'package:test/test.dart';

String tableName = 'simple_data';

void main() async {
  var poolSettings = PoolSettings(
    maxConnectionCount: 10,
    queryTimeout: const Duration(minutes: 1),
    sslMode: SslMode.disable,
  );
  var pgPool = Pool.withEndpoints(
    [
      Endpoint(
        host: 'localhost',
        port: 5432,
        database: 'serverpod_test',
        username: 'postgres',
        password: 'password',
      )
    ],
    settings: poolSettings,
  );

  tearDownAll(() async {
    await pgPool.close();
  });

  test('Multiple asynchronous request with transactions', () async {
    await pgPool.execute('INSERT INTO $tableName (num) VALUES (1);');

    var first = pgPool.execute('SELECT 1;');
    // var second = pgPool.execute('SELECT 1;');

    // await Future.wait([first, second]);
    await Future.wait([first]);

    var firstTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var secondTransaction = pgPool.runTx((ctx) async {
      var result = await ctx.execute('SELECT * FROM $tableName;');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    var [result1, result2] =
        await Future.wait([firstTransaction, secondTransaction]);

    print(result1);
    print(result2);
    expect(result1.isEmpty, isNot(result2.isEmpty),
        reason: 'One of the transactions should return not return');
  });
}
```

**Comment by SandPod** [comment]
It seems like the transactions are queued if no asynchronous transaction is performed before the transactions starts.

This code block:
```dart
    var first = pgPool.execute('SELECT 1;');
    // var second = pgPool.execute('SELECT 1;');

    // await Future.wait([first, second]);
    await Future.wait([first]);

    print('Starting first transaction');
    var firstTransaction = pgPool.runTx((ctx) async {
      print('Running first transaction');
      var result = await ctx.execute('SELECT * FROM $tableName;');
      Future.delayed(Duration(seconds: 2));
      print('First transaction result $result');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    print('Starting second transaction');
    var secondTransaction = pgPool.runTx((ctx) async {
      print('Running second transaction');
      var result = await ctx.execute('SELECT * FROM $tableName;');
      Future.delayed(Duration(seconds: 2));
      print('Second transaction result $result');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });
```

Gives this print:
```bash
Starting first transaction

Starting second transaction

Running first transaction

First transaction result [[204, 1]]

Running second transaction

Second transaction result []
```

While this code block (same transaction code block but we run and await multiple asynchronous requests before):
```dart
    var first = pgPool.execute('SELECT 1;');
    var second = pgPool.execute('SELECT 1;');

    await Future.wait([first, second]);
    // await Future.wait([first]);

    print('Starting first transaction');
    var firstTransaction = pgPool.runTx((ctx) async {
      print('Running first transaction');
      var result = await ctx.execute('SELECT * FROM $tableName;');
      Future.delayed(Duration(seconds: 2));
      print('First transaction result $result');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });

    print('Starting second transaction');
    var secondTransaction = pgPool.runTx((ctx) async {
      print('Running second transaction');
      var result = await ctx.execute('SELECT * FROM $tableName;');
      Future.delayed(Duration(seconds: 2));
      print('Second transaction result $result');
      await ctx.execute('DELETE FROM $tableName;');
      return result;
    });
 ```
 
 Gives these prints:
 ```bash
 Starting first transaction

Starting second transaction

Running first transaction

Running second transaction

First transaction result [[205, 1]]

Second transaction result [[205, 1]]
 ```

**Comment by isoos** [comment]
> It seems like the transactions are queued if no asynchronous transaction is performed before the transactions starts.

(Will review this possibly later this week, but a quick answer until then.)

If you are using a single connection, the current implementation will run statements one-by-one in a non-concurrent queue (and also transactions are also queued on a single connection). The `Pool`, depending on the max connection setting, may try to reuse only the existing connections, and also gets queued.

**Comment by SandPod** [comment]
OK! That makes sense.

What is the expected behavior around a library transaction in the non-concurrent queue? Is the whole transaction considered a queue object or are the individual statements in the transaction added to the queue (as well as the begin and commit statement)?

**Comment by SandPod** [comment]
I'm suspecting that this test in the library would break if multiple asynchronous queries are initiated on the same connection before the transactions are started: https://github.com/isoos/postgresql-dart/blob/4192177496a2af461800f0370ebcb0ea9cbeb244/test/transaction_test.dart#L87

**Comment by SandPod** [comment]
I created a draft PR with tests in the repo that validate the issue: https://github.com/isoos/postgresql-dart/pull/307

The problem is not with Postgres transactions but rather with the library transaction queue object. It seems like the queue objects integrity is broken If multiple concurrent transactions are performed before the transaction is started.

Since the test uses the same connection (from the pool) for executing the queries I would expect the same behavior as a direct connection.

And it is especially strange that the transaction integrity is preserved if no concurrent request is performed before.

**Comment by isoos** [comment]
I think you misinterpret the meaning of `runTx`: it is not meant to coordinate between the Dart client codes, instead, it is just a regular callback that - on the connection that is given to it - runs a `BEGIN TRANSACTION` at the start, and `COMMIT` or `ROLLBACK` at the end of the block, depending on clean exit or an exception being thrown. There is no coordination between these callbacks otherwise.

**Comment by SandPod** [comment]
OK, I think you are correct.

However, it makes me a bit confused about this test for a single connection: https://github.com/isoos/postgresql-dart/blob/4192177496a2af461800f0370ebcb0ea9cbeb244/test/transaction_test.dart#L87

What are we guaranteeing when we say that two simultaneous transactions cannot be interwoven? That made me assume we had some form of transaction queue object.

**Comment by isoos** [comment]
> What are we guaranteeing when we say that two simultaneous transactions cannot be interwoven?

A connection accepts `run`, `runTx`, `execute` and other operations. Every one of these (executed on a single connection object) will lock the object for themselves and the others won't run until that lock is released. This is a an implementation detail, but in theory the client could send all of the queries to the server, but that makes the result separation much more complex, so we are only sending them one-at-a-time. (The server would only process them one-at-a-time, the performance difference is minimal).

> That made me assume we had some form of transaction queue object.

Transaction is a database-level consistency guarantee with different levels, e.g. https://www.postgresql.org/docs/16/transaction-iso.html
The client supports only the initialization (e.g. setting the isolation level) and the auto-closing of the transactions.

**Comment by SandPod** [comment]
Awesome, thank you for the detailed explanation and taking the time to bring me along @isoos 🌟 

Will close this as I now understand this is working as expected and that I had made a couple of wrongful assumptions.
