### ISSUE TITLE
Should I use PostgreSQLException? I noticed it uses the legacy package

### ISSUE THREAD

**Issue by ember11498** [isoos/postgresql-dart#308]
Should I use the PostgreSQLException? I migrated all my code from legacy to the most updated version (3.1.0). But whenever I use PostgreSQLException it still imports the postgres/legacy and not the postgres/postgres. Is that ok?

**Comment by isoos** [comment]
> I migrated all my code from legacy to the most updated version (3.1.0).

Since you've migrated, you should use `PgException` instead. Btw. in `legacy.dart` we are using the following typedef:
```
typedef PostgreSQLException = ServerException;
```

where `ServerException` is a subclass of `PgException`, so you should have no further issues with it.

**Comment by ember11498** [comment]
so i guess i should work with ServerException since it has a lot more detail

**Comment by ember11498** [comment]
I basically want to get the exceptions when inserts fail basically mostly due to unique constraint violation or char lenght and stuff like that. So I basically just use ServerException and then everything else can fall in a general catch(e)
