### ISSUE TITLE
Bulk Insert approach

### ISSUE THREAD

**Issue by zambetpentru** [isoos/postgresql-dart#314]
Greetings,

Is there a recommended way to bulk insert rows into Postgres via this package? I have it inserting rows with the V3 API now one by one and I'm wondering if there is a recommend way to do bulk insert of rows via the API (without building a set of Insert Values manually).

**Comment by isoos** [comment]
One way to make it more efficient is to use reusable queries through https://pub.dev/documentation/postgres/latest/postgres/Session/prepare.html (and then `Statement.run`).

Another option is to insert multiple rows inside a single `INSERT` statement (as you seem to suggest).

Depending on the locking of the tables and the distribution of the keys, you may also use multiple concurrent connections.

Other than that, you are limited with the protocol and how postgres processes the data. There is also the `COPY` command that you may find useful: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by zambetpentru** [comment]
Okay that's clear thank you! I just wanted to check I wasn't missing something like SQLBulkCopy in SQL Server.
