### ISSUE TITLE
v3 Pool Concurrency

### ISSUE THREAD

**Issue by zambetpentru** [isoos/postgresql-dart#315]
Can you please provide me some guidance as I can't see to find the concurrency variable in the postgres v3 integrated pool that is in the postgres_pool package?

**Comment by isoos** [comment]
`package:postgres_pool` is for the `v2` version of the client API. V3 has its own `Pool` class, which, after it has been created is just a drop-in replacement for the `Connection` (or at the lower levels the `Session` interface). E.g. one example is this test file:
https://github.com/isoos/postgresql-dart/blob/master/test/pool_test.dart#L33

**Comment by zambetpentru** [comment]
Hi, 

Ah perfect, it is **maxConnectionCount**: 8    instead of what used to be ..concurrency = 8

Thanks!
