### ISSUE TITLE
Issue with insert and returning

### ISSUE THREAD

**Issue by ethArek** [isoos/postgresql-dart#33]
Hello. 
I started using this library for my postgresql queries but I don't know how to get inserted record from INSERT query. 
Example:
```
void create(String userId, String text) async {
    var query =
        'INSERT INTO notes (user_id, text) VALUES (${PostgreSQLFormat.id('userId', type: PostgreSQLDataType.uuid)}, ${PostgreSQLFormat.id('text', type: PostgreSQLDataType.text)}) RETURNING (id, text, created_at)';
    var result = await db.connection.query(query, substitutionValues: {'userId': userId, 'text': text});

    print(jsonEncode(result));
 }
```

prints
`[[[0,0,0,3,0,0,11,134,0,0,0,16,5,206,14,98,66,178,74,48,171,21,125,155,177,116,219,206,0,0,0,25,0,0,0,13,109,121,32,102,105,114,115,116,32,110,111,116,101,0,0,4,90,0,0,0,8,0,2,127,100,172,133,115,143]]]`

How can I get inserted row in postgresql-dart library? Does it support "RETURNING"?

**Comment by isoos** [comment]
It should support returning, as I've used it a lot, and we also have tests using `RETURNING`. What's in your `result.columnDescriptions`?

Also: it looks like `RETURNING` doesn't require parentheses, what happens if you leave out and just use `RETURNING id, text, created_at`?

**Comment by ethArek** [comment]
> Also: it looks like RETURNING doesn't require parentheses, what happens if you leave out and just use RETURNING id, text, created_at?

That's it. I removed parentheses after RETURINING and it started working. Thank you for help :)
