### ISSUE TITLE
Getting an "Instance of 'UndecodedBytes'", although the column type in the db table is json[]

### ISSUE THREAD

**Issue by tahat-h** [isoos/postgresql-dart#330]
I have a table in PostgreSQL that has a column like "json[]", when I write data to it, everything is fine, but when I try to get them, I get an Instance of 'UndecodedBytes'.

Description of the GrammarProgress class:
```dart
@JsonSerializable(explicitToJson: true)
class GrammarProgress {
  GrammarProgress({
    required this.passed,
    required this.section,
    required this.attempts,
  });

  final bool passed;
  final int section;
  final int attempts;

  static GrammarProgress fromJson(Map<String, dynamic> json) =>
      _$GrammarProgressFromJson(json);
  Map<String, dynamic> toJson() => _$GrammarProgressToJson(this);
}
```

Generating a list with instances of this class:
```dart
final grammarList = List.filled(
    13,
    jsonEncode(
      GrammarProgress(
        passed: false,
        section: 0,
        attempts: 0,
      ),
    ),
  );
```

Inserting into a table:
```dart
await txSession.execute(
      '''
      INSERT INTO grammars (id, progress_list)
      VALUES('$uuid', ARRAY['$grammarList'::json]);
      ''',
);
```
 
 Trying to get a value from a column:
 ```dart
final response = await connection.execute('''
    SELECT progress_list FROM grammars
    WHERE id = '$id';
 ''');
```
 
If you try to output the results of the "response" variable, the answer will be: [[Instance of 'UndecodedBytes']]
```dart
print(response);
```

If I create a table with a column that has a `json` type, then everything works well, I can both write values to the table and get them from there.

And if I set the column type to `json[]`, then I can only write it down, but I won't be able to get it.

Tell me, please, what am I doing wrong?

![Output](https://github.com/isoos/postgresql-dart/assets/123538624/07854166-454f-4526-8f6c-71763c64fe3b)
![pgAdmin](https://github.com/isoos/postgresql-dart/assets/123538624/c06a1e17-e228-4423-b93d-d09e152d09a8)

**Comment by isoos** [comment]
We do support `jsonb[]` see https://pub.dev/documentation/postgres/latest/postgres/Type/jsonbArray-constant.html, however, we don't have a direct support for `json[]`. If you are interested adding support for it, I think https://github.com/isoos/postgresql-dart/pull/304 and https://github.com/isoos/postgresql-dart/pull/305 were recent PRs that you could use as baseline, and with a test or two I'm happy to merge such PRs.

**Comment by isoos** [comment]
Aside question: is there any benefit of using `json/json[]` instead of `jsonb/jsonb[]`?

**Comment by tahat-h** [comment]
> Aside question: is there any benefit of using `json/json[]` instead of `jsonb/jsonb[]`?

Json does not have any clear advantages over jsonb.

Jsonb is usually the preferred format because it requires less space for objects, can be indexed, and is processed faster because it does not require repeated parsing.

Thanks for the prompt response, I will use jsonb!)
