### ISSUE TITLE
Boolean values inside boolean[] collapse into a single value

### ISSUE THREAD

**Issue by tahat-h** [isoos/postgresql-dart#332]
There is a table "sentences_listening", it has columns "easy_list", "middle_list", "hard_list".

When adding values to it, everything happens great and if you check through pgAdmin, you can see that they are all saved in the database.

But if I try to get the values from the columns, I get lists that contain only 1 element, although each column contains a list with 20 elements.

Maybe this is because in Postgresql they are written as {{f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f}}, and not {[f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f]}, therefore, Dart treats them as a Set, therefore it outputs a list with a single value, and not with everyone?

I write the values in the table:
```Dart
await txSession.execute(
      '''
      INSERT INTO sentences_listening (id, easy_list, middle_list, hard_list)
      VALUES(
        '$uuid',
        ARRAY[${List.filled(listeningEasyList.length, false).toList()}],
        ARRAY[${List.filled(listeningMiddleList.length, false).toList()}],
        ARRAY[${List.filled(listeningHardList.length, false).toList()}]
      );
      ''',
    );
```

Getting the values from the table:
```Dart
final response = await connection.execute(
    '''
    SELECT easy_list, middle_list, hard_list from sentences_listening
    WHERE id = '$userId';
    ''',
  );
```

If you output the value of the response variable, you get: [[[false], [false], [false]]].

What could be the reason for this behavior?

![output](https://github.com/isoos/postgresql-dart/assets/123538624/f3216d02-9d13-494f-8c5f-95d667c6c3a4)
![pgAdmin](https://github.com/isoos/postgresql-dart/assets/123538624/861d901c-9cf9-47ba-ad5b-77fe307aa1ea)

**Comment by isoos** [comment]
Not sure about this query format, but why not use the `bool[]` support?
https://pub.dev/documentation/postgres/latest/postgres/Type/booleanArray-constant.html

`execute('INSERT INTO x VALUES ($1)', parameters: Type.booleanArray([false, false, false]))`;

**Comment by tahat-h** [comment]
> Not sure about this query format, but why not use the `bool[]` support? https://pub.dev/documentation/postgres/latest/postgres/Type/booleanArray-constant.html
> 
> `execute('INSERT INTO x VALUES ($1)', parameters: Type.booleanArray.value([false, false, false]))`;

That's right, I haven't tried it with this insertion format.

I inserted the values into the table, with the format that you specified — everything worked out, thank you very much, have a nice day!)

**Comment by tahat-h** [comment]
Thanks again!)
