### ISSUE TITLE
Query streaming

### ISSUE THREAD

**Issue by ivanmem** [isoos/postgresql-dart#335]
Does this library have similar functionality? I am attaching the readme from the [postgresql2](https://pub.dev/packages/postgresql2#query-streaming) library.

```md
Connection.query() returns a Stream of results. 
You can use each row as soon as it is received, or you can wait till they all arrive by calling Stream.toList().
```

I need to load records sequentially and, if necessary, cancel the request.

**Comment by isoos** [comment]
https://pub.dev/documentation/postgres/latest/postgres/Session/prepare.html returns a `Statement` object, which after binding https://pub.dev/documentation/postgres/latest/postgres/Statement/bind.html gets you a stream.

Note: I don't really remember if this cancel the request on the database side, or just ignores the returned rows on the client side. Maybe @simolus3 can answer that?

**Comment by simolus3** [comment]
We'd ignore subsequent rows but effectively keep the connection locked until postgres reports that the statement is done, so there's not really a benefit to cancelling a statement subscription.

I don't think there's an effective way in the protocol to cancel running queries (I'm sure there are some tricks to kill the involved postgres process but that sounds super hacky and is probably not something we should do).

**Comment by ivanmem** [comment]
@isoos, ResultStream seems to load all rows even if I take 300 rows from there. Is it possible to load rows in parts? I need maximum optimization so that nothing unnecessary is loaded. 

```dart
Future<List<Map>> getRows(int? count) {
    final stream = _stream!;
    return stream
        .skip(_table?.rows.length ?? 0)
        .take(count ?? intMaxValue)
        .map((resultRow) => resultRow.toColumnMapDynamic())
        .toList();
  }
```

**Comment by isoos** [comment]
In this case `skip()` won't skip rows at the server, only at the client, and the server is returning everything - unoptimized. If you want to optimize your query performance, use pagination, but not offset based ones, nor client based ones, rather using natural pagination key conditions.

**Comment by ivanmem** [comment]
Thanks I got it. I need cursors. Apparently they can only be used by manually writing them in an SQL query.
