### ISSUE TITLE
long-lived transaction

### ISSUE THREAD

**Issue by ivanmem** [isoos/postgresql-dart#336]
How to get a transaction session, but without using `connection.runTx`? I need a long-lived transaction that does not terminate itself. I want to use DECLARE CURSOR for lazy loading in the table and then load as many records as I need on the button.

**Comment by isoos** [comment]
You can always use `Connection` and execute whatever statement you want, e.g. `BEGIN TRANSACTION`.

However, based on your second sentence, you want to keep this open waiting for use interaction, which - in case of mobile apps or web backend server apps - is an anti-pattern and I'd advise against it.
