### ISSUE TITLE
What is the recommended way to insert multiple rows into a postgresql db?

### ISSUE THREAD

**Issue by atreeon** [isoos/postgresql-dart#34]
In sql I'd make user of the values clause to insert multiple rows
```
INSERT INTO Entries (id, name)
VALUES 
(1, 'blah'),
(2, 'blim
(3, 'blib'),
```
but I don't see a way to paramaterise my input this way.  Possibly I could use the transaction method but this won't be as efficient:
```
      await cn.transaction((c) async {
        await c.query("INSERT INTO table (id) VALUES (@a:int4)", substitutionValues: {"a" : 1});
        await c.query("INSERT INTO table (id) VALUES (@a:int4)", substitutionValues: {"a" : 2});
        await c.query("INSERT INTO table (id) VALUES (@a:int4)", substitutionValues: {"a" : 3});
      });
```
I can take a hit on efficiency, it is not ideal but I can do it, but just wondered if there was a way to insert multiple rows in one go?  Maybe something like this?  Or is there something more built in?
```
        await c.query("INSERT INTO table (id) VALUES (@a:int4), (@b:int4}, (@c:int4)", //
            substitutionValues: {
              "a": 1,
              "b": 2,
              "c": 3,
            });```

**Comment by isoos** [comment]
There is no built-in method for this, but your last example is pretty much the standard way of doing it, at least that of I know.

**Comment by isoos** [comment]
^ ... the standard way of inserting multiple rows. Bear in mind that depending on your indexes, transactions or other requirements, your second example may be just as good.

**Comment by atreeon** [comment]
thanks for your input :)  I think the code for the second option might be a bit more readable so I think I'll go with that for the moment.
