### ISSUE TITLE
Question : postgres connection with isolate(s)

### ISSUE THREAD

**Issue by x4080** [isoos/postgresql-dart#36]
I'm trying to build server side postgres api, and I wondered how to handle postgres connection with isolate(s),
since function cannot be shared from main to isolate, it seems the answer would be to create pg connection inside isolate.

And it still fine, but the problem becomes when trying to close the server, how to close the pg connection inside isolate when
the server close ?

Anyone has ideas ? 

TIA

**Comment by isoos** [comment]
One usually useful option is to use `pgbouncer` as an intermediary between the application's connection pool and the server. For example: you may configure your app to use e.g. 16 connection per isolate, and running 8-8 isolates on 10 nodes, but your server may not accept all the 1280 connections. A pgbouncer sitting in-between could be configured to use e.g. 128 connections toward the server, and with that, you can try to maximize it at your app/isolate level, and also at your db server.

**Comment by x4080** [comment]
@isoos Thanks for quick answer, so in the dart side, is it ok to keep the connection open on the isolate ?

**Comment by isoos** [comment]
Yeah, exactly: you should keep the connection open, regardless of the isolate. You've found `package:postgres_pool` already, that's exactly for this case :)

**Comment by x4080** [comment]
@isoos Thanks!
