### ISSUE TITLE
error messages are not coming in utf8

### ISSUE THREAD

**Issue by luciano-cervantes** [isoos/postgresql-dart#40]
error messages are not coming in utf8 standard. I had to do it this way to fix it `return utf8.decode(e.message!.codeUnits);`.  Is there any possibility of fixing this?

**Comment by isoos** [comment]
Is the database connection set to use utf8?
In any case, if you can debug and fix this locally, PRs are welcome :)

**Comment by isoos** [comment]
I also have a branch that started to make the encoding configurable, it may help here:
https://github.com/isoos/postgresql-dart/tree/encoding

**Comment by isoos** [comment]
The new v3 API has better encoding support.
