### ISSUE TITLE
Is the package support the newest PostgresSQL

### ISSUE THREAD

**Issue by kfiross** [isoos/postgresql-dart#42]
Is the package support with the PostgresSQL 14.1?

**Comment by isoos** [comment]
The CI is on `postgres:latest`, and it was running yesterday on a PR, so I would assume it works :)
If not, please open an issue.

**Comment by kfiross** [comment]
I just wondered if I can connect directly to Supabase PostgresSQL

**Comment by isoos** [comment]
I don't see why you wouldn't be able to... Please report back if something is failing.
