### ISSUE TITLE
is this really secure?

### ISSUE THREAD

**Issue by Riyaz7364** [isoos/postgresql-dart#44]
I want to know about plugging security. Is this a secure way, putting Postgres username and password hardcoded? I mean those Who have the knowledge to decode the app can easily see the account and do anything with that. What is the matter of the plugging, I mean why this plugging creates,

**Comment by isoos** [comment]
It is stated in a lot of places, that it is not safe to connect to Postgres from a mobile app, as people may be able to inspect the username and password. This package is intended for server side use, and it is not a goal to handle or deal with mobile app security in that regard. I haven't really followed other solutions, but if you have one to contribute, I'm happy to review and merge it.
