### ISSUE TITLE
WHERE...IN... query support?

### ISSUE THREAD

**Issue by Fraa-124** [isoos/postgresql-dart#46]
Hello, 

1.
   is there support for 'where in' queries?
```dart
ctx.mappedResultsQuery('select * from users where id IN(@ids)', substitutionValues: {'ids': ids}));
```

2. Can I use a query like this? without substitutionValues param.
```dart
 ctx.mappedResultsQuery('select * from users where id = "$id");
```

**Comment by isoos** [comment]
My workaround so far was to use `... IN(@p1, @p2, @p3)', substitutionValues: {'p1: x, 'p2': y, 'p3': z}`.
We we'd need a smarter query builder, or a dedicated list type that converts the values automatically.

**Comment by Fraa-124** [comment]
It works, thank you.

**Comment by bryanoltman** [comment]
This issue is a bit old, but I'm running into this now and not seeing anything providing lists as parameters, so I'd like to reopen if this hasn't been implemented. Ideally, I could write something like:

```dart
final ids = [1, 2, 3];
await session.execute(
  'SELECT * from user where id in @ids', parameters: ids
);
```
and have that execute the query:
```sql
SELECT * from user where id in (1, 2, 3)
```

**Comment by xvrh** [comment]
The syntax is `select * from user where id = any(@ids)`. It works already.

**Comment by bryanoltman** [comment]
Awesome, thank you! Couldn't find that in the docs.
