### ISSUE TITLE
fields of type timestamp with time zone

### ISSUE THREAD

**Issue by punteronulo** [isoos/postgresql-dart#69]
When I do a select from a timestamp with time zone type field, it always returns it with two hours difference (the ones that correspond to my time zone) but if I do it from pgadmin I get the correct time.

Is it a bug? How should I treat this kind of fields.
sorry for my bad english (google translate)

**Comment by isoos** [comment]
Could you please create an example test case?

I'm not really sure if this is a bug or expected, but until we figure it out, maybe you should try casting it when selecting? `stored_timestamp AT TIME ZONE 'UTC'` should probably do it...

**Comment by punteronulo** [comment]
Sorry for the delay, I was traveling. I made a small example:

used table, created using pgAdmin 4:

CREATE TABLE test
(
    formato character varying,
    fecha timestamp with time zone
);

3 insert from code:

final PostgreSQLConnection conexion = PostgreSQLConnection(host, port, dbName, username: usr, password: pw);

await conexion.query("insert into test (formato, fecha) values ('code - now', now())");
await conexion.query("insert into test (formato, fecha) values ('code - manual', '2022/09/23 11:25:00')");
await conexion.query("insert into test (formato, fecha) values ('code - manual +2', '2022/09/23 11:25:00+2')");

3 insert from pgAdmin 4:

insert into test (formato, fecha) values ('pgadmin - now', now());
insert into test (formato, fecha) values ('pgadmin - manual', '2022/09/23 11:25:00');
insert into test (formato, fecha) values ('pgadmin - manual +2', '2022/09/23 11:25:00+2');

output from code:

PostgreSQLResult result = await conexion.query('select * from test');
for (int i = 0; i < result.length; i++) {
  print(result[i]);
}

[code - now,                2022-09-23 09:26:34.160857Z]
[code - manual,            2022-09-23 11:25:00.000Z]
[code - manual +2,       2022-09-23 09:25:00.000Z]
[pgadmin - now,           2022-09-23 09:27:32.534984Z]
[pgadmin - manual,      2022-09-23 09:25:00.000Z]
[pgadmin - manual +2, 2022-09-23 09:25:00.000Z]

output from pgAdmin 4:

select * from test

"code - now"	              "2022-09-23 11:26:34.160857+02"
"code - manual"	      "2022-09-23 13:25:00+02"
"code - manual +2"        "2022-09-23 11:25:00+02"
"pgadmin - now"	      "2022-09-23 11:27:32.534984+02"
"pgadmin - manual"	      "2022-09-23 11:25:00+02"
"pgadmin - manual +2"  "2022-09-23 11:25:00+02"

timezone 'Europe/Madrid' (+2)

when i do the select from the code i always get 2 hours less

Dart 2.18.1
postgres: 2.5.2
PostgreSQL 14
Windows 10

**Comment by osaxma** [comment]
All times given by the package are in UTC (hence the `Z` at end of the printed timestamps).

You can get the local time using `DateTime.toLocal()` such as:

```dart
for (int i = 0; i < result.length; i++) {
  final date = (result[i][1] as DateTime).toLocal();
  print(date);
}
```

**Comment by punteronulo** [comment]
Ok, so everything is correct, it was my ignorance on the subject. Great job with this package. Thank you very much
