### ISSUE TITLE
Requires allowClearTextPassword set to true??

### ISSUE THREAD

**Issue by mprogers** [isoos/postgresql-dart#71]
This only seems to work if I set allowClearTextPassword to true - otherwise I get this error message -- type 3 connections disabled. Set AllowClearTextPassword flag on PostgreSQLConnection to enable this feature.

I can't really, in 2022, send clear text anything. Any ideas?

    databaseConnection = PostgreSQLConnection(widget.databaseHost, widget.databasePort, widget.databaseName,
        queryTimeoutInSeconds: 3600,
        timeoutInSeconds: 3600,
        username: widget.userName,
        password: widget.password,
        useSSL: true,
        allowClearTextPassword: true);
  }

**Comment by isoos** [comment]
@mprogers: are you using a local postgres instance, or a hosted one?

**Comment by mprogers** [comment]
Hosted.Sent from my iPhoneOn Nov 7, 2022, at 2:08 AM, István Soós ***@***.***> wrote:﻿
@mprogers: are you using a local postgres instance, or a hosted one?

**Comment by isoos** [comment]
#20 was created to connect to a hosted azure instance. I'd assume that with `requireSsl` the connection is using SSL, and while the password itself is cleartext, it is encrypted over the network, but I have zero experience with it. I'm happy to review and accept PRs if you think you can improve the current code.
