### ISSUE TITLE
Escape @ signs in query

### ISSUE THREAD

**Issue by schultek** [isoos/postgresql-dart#80]
I would like a way to escape '@' signs in a query that should not be treated as a substitution parameter.

Say I have an email like `bob@123.com` in my query and use a substitution parameter `@1: somevalue` for something else. Then either the query fails with an error or I have some wrong data in the database.

- `db.query('INSERT INTO "email" VALUES (@b), (\'a@b.com\')', substitutionValues: {'b': 'someval'})` 
  leads to error 
  `PostgreSQLSeverity.error 08P01: bind message supplies 2 parameters, but prepared statement "000000000000" requires 1 `
- `db.query('INSERT INTO "email" VALUES (@b), (\'a@@b.com\')', substitutionValues: {'b': 'someval'})` 
  leads to no error, but `a@@b.com` is inserted into the database as is

It would be nice to have a way to escape @ signs independently of whether there is a parameter using the same name or not.

This is somewhat related to #72, as a more low-level api to define parameters would also be fine. 
I'm developing an ORM and currently can't use query parameters because of this.

**Comment by isoos** [comment]
I think this is a good candidate for the v3 API requirement list (see also #74).

At the moment there is no good solution for it. You may use another substituted value in place of `'a@b.com'`, so that it gets recognized/escaped properly.

**Comment by simolus3** [comment]
In the V3 API, we will ignore at signs in comments, string literals and escaped identifiers.  The API also allows not scanning the query for at signs at all, which may be helpful when writing an ORM that manages variables itself.

Do you see another use case for escaping at signs once they are ignored in those places?

**Comment by ailabs-software** [comment]
Will @> and <@ operators work in the V3 API (they did not work when I tested in the current API as they were escaped)?

**Comment by ailabs-software** [comment]
@simolus3 I recreated my test and realised I'm actually wrong! Glad to see the v3 improvements coming though.

**Comment by isoos** [comment]
Closing as the v3 queries have better escape support now.
