### ISSUE TITLE
inserted dates are incorrect

### ISSUE THREAD

**Issue by moonlitknight** [isoos/postgresql-dart#82]
The following code inserts a date 1.5 hours old.

```
static const insertMessageSql ="insert into messages values (default, 'dart', 'now') returning msg_id";
var rs = await db.query(insertMessageSql); // query because I want the returned message ID.
```
psql output
```
59372194 |   java            | 2023-01-29 19:20:52.703+00    | 
59372192 |   dart            |  2023-01-29 17:45:50.550511+00 |
59372160 |   java            | 2023-01-29 19:17:36.813+00    | 
```

To explain the psql output: I am inserting messages from a Java app and also from my postgresql-dart. The first column is an incrementing sequence number. Thus the dart insert took place sometime between 19:17 and 19:20, yet the timestamp being inserted is 17:45.

Could this be relevant? https://www.postgresql.org/docs/current/datatype-datetime.html which says "While the input strings now, today, tomorrow, and yesterday are fine to use in interactive SQL commands, they can have surprising behavior when the command is saved to be executed later, for example in prepared statements, views, and function definitions. The string can be converted to a specific time value that continues to be used long after it becomes stale. "

**Comment by isoos** [comment]
I haven't used it like that, but it could be related or the timezone of the session could be different. It is better to use UTC only in both the data type (timestamp without timezone) and the queries being executed.

**Comment by moonlitknight** [comment]
It's not a TZ issue. As you can see, the delta is 1hour 33 mins (not 1 hour or 8 hours) and I use UTC throughout my app.

I can work around it by using dates from the client `DateTime.now().toIso8601String()` instead of `'now'` , but this gives me problems in the future as I have no control over the time or timezone of the containers the client app is executing in. It's important for me that the database is the single source of truth for current time.

**Comment by moonlitknight** [comment]
I've just two more tests, 10 secs apart. Here is the result ...
```
59372467 |           8 | foot1 5047 | N           | 2023-01-29 17:45:50.550511+00 
59372466 |           8 | foot1 5047 | N           | 2023-01-29 17:45:50.550511+00
```

So it's pretty clear that there is a stale date being used in some kind of prepared statement.

**Comment by isoos** [comment]
It is possible. A few things to try:
- `now()` instead of `'now'`
- `allowReuse: false` or,
- `useSimpleQueryProtocol: true` or
- use the `execute` method instead of the query.

**Comment by moonlitknight** [comment]
The first option `now()` works. My guess is the 2nd would also work. Not sure about 3. Option 4 is not an option for me because I need the returned value.

I'm happy to close the issue  - many thanks for the rapid resolution.
