### ISSUE TITLE
Type conversion fails for list of JSON with nullable parameters

### ISSUE THREAD

**Issue by DamienLeon** [isoos/postgresql-dart#91]
Hi,
I have an ```AddressModel``` class with ```fromJson``` expecting a type of ```Map<String, dynamic>``` as few parameters are nullable. I store ```List<AddressModel>``` in another model. I use `Stormberry` package as an ORM for which I have the `TypeConverter` for `AddressModel` as follows which basically calls the `PostgresBinaryEncoder().convert()` and `PostgresBinaryDecoder().convert()` functions in the `binary_codec.dart` file.

```
class AddressConverter extends TypeConverter<Address> {
  const AddressConverter() : super('jsonb');

  @override
  Map<String, dynamic> encode(Address value) => value.toJson();

  @override
  Address decode(dynamic value) {
    if (value is Map<String, dynamic>) {
      return Address.fromJson(value);
    } else {
      log(value.toString(), name: "Address Parsing Error");
      throw Exception("Parsing error: Unable to parse");
    }
  }
}
```
-----
Now, the issue is that when the type conversion happens, it expects a ```List<Object>``` but finds a ```List<dynamic>```. The workaround is to manually change ```List<Object>``` to ```List<dynamic>``` in the `PostgresBinaryEncoder().convert()` function as follows:

```
case PgDataType.jsonbArray:
        {
          if (input is List<dynamic>)  // Here, List<Object> is changed to List<dynamic>
          {
            final objectsArray = input.map((v) => utf8.encode(json.encode(v)));
            return writeListBytes<List<int>>(objectsArray, 3802, (item) => item.length + 1,
                (writer, item) {
              writer.writeUint8(1);
              writer.write(item);
            });
          }
          throw FormatException(
              'Invalid type for parameter value. Expected: List<Object> Got: ${input.runtimeType}');
        }
```

The code runs fine after his change and the data entry is added to the database.

-----

```
Flutter 3.7.11 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f72efea43c (7 days ago) • 2023-04-11 11:57:21 -0700
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

stormberry: ^0.13.0 // postgres: 2.6.1
```

**Comment by isoos** [comment]
I don't see much issue with such a change. Could you please create a PR for it?
Note: you've mentioned the reference of `PostgresBinaryEncoder`: are you using it directly for any reason? Or just tracked it through the debugging of the issue?

**Comment by DamienLeon** [comment]
I just tracked it while debugging. Since `Object` does not allow null values and the model here is nullable, this is causing the issue I believe.

**Comment by isoos** [comment]
@DamienLeon: was this issue fixed or still pending?

**Comment by DamienLeon** [comment]
It's not fixed. I manually change the datatype from Object to dynamic. It works then.
