### ISSUE TITLE
Any possibility to implement executing a prepared statement with question mark placeholder style similar to PDO and support for win1252 encoding

### ISSUE THREAD

**Issue by insinfo** [isoos/postgresql-dart#93]
@schultek @isoos @simolus3 @osaxma 

Any possibility to implement executing a prepared statement with question mark placeholder style similar to PDO and support for win1252 encoding

### something like this
```dart
    var con = CoreConnection(
        'user',
        database: 'dataBaseTest',
        host: 'localhost',
        port: 5432,
        password: '123456',     
        textCharset: 'win1252',  
    );

    await con.connect();

    await ctx.queryUnnamed(
      'INSERT INTO test_arrays (name, varchar_array_type) VALUES (?, ?);',
      [ 'Vagner',   ["João", '''Isaque Sant'Ana''']  ],
      placeholderIdentifier: PlaceholderIdentifier.onlyQuestionMark,
    );
    
    await con.close();
```

i have implemented support for this in my "dargres" driver, but i don't know this code base to know where and how i should implement this in this driver, if you can provide guidance for this i will try to implement this

I'm trying to port the eloquent PHP library into dart and would like to implement it with other drivers
https://pub.dev/packages/eloquent

**Comment by simolus3** [comment]
It is supported in the v3 API: https://github.com/isoos/postgresql-dart/blob/0e3e4ffd3c399f2ff5b0eb4679240057e5bc5c9c/example/v3/example.dart#L14-L21

**Comment by insinfo** [comment]
@simolus3  
I made the necessary changes to be able to change the encoding and made a pull request
https://github.com/isoos/postgresql-dart/pull/94

**Comment by insinfo** [comment]
I will implement support for question mark placeholder style similar to PDO later and then I will make a pull request ok

**Comment by insinfo** [comment]
it seems that the v3 API is not finalized yet correct?

I saw that PostgresTextDecoder still doesn't handle all postgresql types

**Comment by insinfo** [comment]
implemented executing a prepared statement with question mark placeholder style similar to PHP PDO

```dart
 final results = await connection.query(
        ' SELECT * FROM public.table_example LIMIT ?',
        substitutionValues: [2000], placeholderIdentifier: 
        PlaceholderIdentifier.onlyQuestionMark);
```
waiting for you to merge the last pull https://github.com/isoos/postgresql-dart/pull/94  request to make this other pull request

https://github.com/insinfo/postgresql-dart-1/blob/master/example/v2/example.dart

**Comment by simolus3** [comment]
I don't maintain this package, so I can't merge your PR on my own. If @isoos thinks my feedback on that PR would help with his decision, I'm happy to take a deeper look at it though.

**Comment by isoos** [comment]
@simolus3: I'd appreciate that, as I'm mostly away from keyboard until mid-next week.

**Comment by insinfo** [comment]
@simolus3  
I made some commits with the suggested changes, I'm testing it in a real application that has a data bank with win1252 encoding and everything seems ok so far
https://github.com/insinfo/postgresql-dart-1

**Comment by simolus3** [comment]
Yeah, I'm saying that we need some way to replicate this in a reproducible test. I think the encoding of a connection can be set with a flag, but that's after the connection has already been opened right? It seems like you have a case where connections are using a non-utf8 encoding by default, is that due to running on Windows or some setup that could be used in a test as well?

**Comment by insinfo** [comment]
@simolus3

I think the test implementation can be like this

## connection_encoding_test.dart
```dart
import 'dart:convert';
import 'package:enough_convert/enough_convert.dart';
import 'package:postgres_fork/postgres.dart';
import 'package:test/test.dart';
void main() {
  late PostgreSQLConnection connection;
  setUp(() async {
    final startConn = PostgreSQLConnection(
      'localhost',
      5435,
      'dart_test',
      username: 'dart',
      password: 'dart',
      encoding: utf8,
    );
    await startConn.open();
    final dbExist = await startConn.query(
        '''SELECT * FROM pg_database WHERE datname = 'dart_test_cp1252';''');
    if (dbExist.isEmpty) {     
        await startConn.query(
            '''CREATE DATABASE dart_test_cp1252 TEMPLATE = template0 ENCODING = 'WIN1252' LC_COLLATE = 'pt_BR.cp1252' LC_CTYPE = 'pt_BR.cp1252';''');
  
    }
    //await connection .query('''CREATE ROLE dart WITH LOGIN SUPERUSER PASSWORD 'dart';''');
    await startConn.query(r''' do
$$
begin
  if not exists (select * from pg_user where usename = 'dart') then
     CREATE ROLE dart WITH LOGIN SUPERUSER PASSWORD 'dart';
  end if;
end
$$
; ''');
    await startConn.close();

    connection = PostgreSQLConnection(
      'localhost',
      5435,
      'dart_test_cp1252',
      username: 'dart',
      password: 'dart',
      encoding: Windows1252Codec(allowInvalid: false),
    );
    await connection.open();
    await connection.query('''SET client_encoding = 'win1252';''');
    await connection.query('''DROP TABLE IF EXISTS public.favorites;''');
    await connection.execute('''
  CREATE TABLE IF NOT EXISTS public.favorites (
  "id" serial4 NOT NULL, 
  "date_register" timestamp(6),
  "description" varchar(255),
  CONSTRAINT "favorites_pkey" PRIMARY KEY ("id")
);
''');

    await connection.query(
      ''' INSERT INTO public.favorites (date_register,description) VALUES ( ? , ? ) returning id ''',
      substitutionValues: [
        DateTime.parse('2023-08-15 16:07:36.000Z'),
        'City Hall of São Paulo - Brazil'
      ],
      placeholderIdentifier: PlaceholderIdentifier.onlyQuestionMark,
    );
  });

  tearDown(() async {
    await connection.close();
  });

  test('select varchar encoding win1252', () async {
    final results = await connection.query(
        'SELECT date_register,description FROM public.favorites LIMIT @l',
        substitutionValues: {'l': 1});

    expect(results, [
      [       
        DateTime.parse('2023-08-15 16:07:36.000Z'),
        'City Hall of São Paulo - Brazil'
      ]
    ]);
  });
}

```

## Dockerfile

```Dockerfile
FROM postgres:14.3
ADD pg_hba.conf /var/lib/postgresql/data/
ADD postgresql.conf /var/lib/postgresql/data/
COPY init.sql /docker-entrypoint-initdb.d/
RUN apt-get update 
RUN apt-get -y install tzdata 
RUN apt-get -y install locales
RUN localedef -i pt_BR -c -f CP1252 -A /usr/share/locale/locale.alias pt_BR.CP1252
RUN echo 'pt_BR.CP1252 CP1252' | tee -a /etc/locale.gen > /dev/null
RUN echo 'pt_BR ISO-8859-1' | tee -a /etc/locale.gen > /dev/null
RUN echo 'pt_BR.UTF-8 UTF-8' | tee -a /etc/locale.gen > /dev/null
RUN locale-gen pt_BR.UTF-8  
RUN locale-gen pt_BR
RUN locale-gen
RUN locale -a

ENV LANG pt_BR.CP1252  
```

## init.sql

```sql
CREATE USER sisadmin WITH SUPERUSER PASSWORD 's1sadm1n';
CREATE USER dart WITH SUPERUSER PASSWORD 'dart';
CREATE DATABASE dart_test;
GRANT ALL PRIVILEGES ON DATABASE dart_test TO dart;
ALTER USER postgres with PASSWORD 'dart';
ALTER USER dart with PASSWORD 'dart';
```

## .github/workflows/dart.yml

```yml

...
      - name: pull postgres image
        run: |          
          docker pull postgres:14.3
          docker build -t custom/postgres:14.3 ./docker
          mkdir ./data
          docker run --rm --name="custom_postgres" -e POSTGRES_PASSWORD=dart -v "./data:/var/lib/postgresql/data:rw" -p 5435:5432 custom/postgres:14.3 & 
        
```

**Comment by isoos** [comment]
Note: question mark-based placeholders may be easy to implement now in the new `Sql` class.
encoding support was added.

**Comment by insinfo** [comment]
question mark-based placeholders will it be implemented in version 3?

**Comment by simolus3** [comment]
Hm, not exactly. You get the choice of this package not modifying the SQL at all (which means that you'll have to use dollar signs instead of question marks since that's what Postgres is using natively) or using named variables (with a custom symbol).

I think we could expand the tokenizer we already have to create the illusion of indexed variables with a different symbol, but I don't understand the benefit over using the existing symbol.

**Comment by insinfo** [comment]
I see several benefits in using question mark-based placeholders, it's cleaner, more succinct than using $1 $2 ... or @label, and it also helps with the portability of SQL backend codes for those who are migrating from PHP/Python and others who use the question mark style, just like me

**Comment by isoos** [comment]
I don't mind supporting it, it helps a certain kind of dynamic query building process, where the different parts may not know about the absolute position of their parameters yet.
